name: Release
on:
  push:
    branches:
      - 'release/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build project
        run: ./gradlew assemble
      - name: Extract version
        run: echo "version=$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_OUTPUT
        id: extract_version_name
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN }}
          tag_name: v${{ steps.extract_version_name.outputs.version }}
          files: ./build/libs/sample-github-actions-${{ steps.extract_version_name.outputs.version }}.jar
          generate_release_notes: true
